import mysql.connector
import db_config


mydb = mysql.connector.connect(
	host=db_config.local_host,
	user=db_config.user,
	passwd=db_config.passwd,
	database=db_config.database	
	)

mycursor = mydb.cursor()


sql = """
CREATE TABLE company (
Name varchar(40),
CUSIP varchar(9),
SecId varchar(10),
FundId varchar(10),
MRFundID varchar(15),
PerfID varchar(15),
Ticker varchar(12),
OldestSh varchar(5),
Advisor varchar(200),
FirmName varchar(100),
BrndName varchar(44),
BrndNmID varchar(10),
InceptDt Date,
GlBrdGrp varchar(13),
GlBrdCat varchar(39),
USCatGrp varchar(20),
MSCat varchar(50),
MSCatID varchar(10),
MSCatStr Date,
MSInsCat varchar(43),
MSRatAll varchar(2),
MSRat3Y varchar(2),
MSRat5Y varchar(2),
MSRat10Y varchar(2),
EqStyleL varchar(12),
EqStyleS varchar(12),
FxStyleL varchar(16),
MSSubAdv varchar(721),
MSSubFee varchar(516),
TeamMgd varchar(3),
MgrHist varchar(5000),
MgrName varchar(1000),
MgrTnrAv Numeric(6,2),
MgrTnrLg Numeric(6,2),
PPBnch varchar(400),
PPBnchID varchar(10),
PPBIncpt Date,
SPBench varchar(400),
AUMShr bigint,
AUMShrDt Date,
FSizeCur bigint,
FSizeDt Date,
hldBondL Int,
hldBondS Int,
hldLong Int,
hldOthrL Int,
hldOthrS Int,
hldStckL Int,
hldStckS Int,
hldT10 numeric(10,6),
hldofInv varchar(3),
hldAT10 numeric(10,6),
hldAT10D Date,
Yld12M numeric(10,6),
Yld12MD Date,
SECYld numeric(10,5),
SECYldD Date,
DivdCur numeric(11,7),
DivdCurD Date,
DivdNAVC numeric(8,4),
PortDate Date,
VirtClss varchar(3),
FeeMgt numeric(10,3),
NExpSAR numeric(7,3),
NExpSARD Date,
ChrgAR numeric(6,3),
ChrgARD Date,
NExpPrs numeric(7,3),
NExpPrsD numeric(7,3),
ObjPros varchar(30),
Fee12b1 numeric(5,3),
TurnRat numeric(10,3),
TurnRatD Date,
CashN numeric(11,6),
AABondN numeric(11,6),
AACashN numeric(11,6),
AAEqN numeric(11,6),
AANUSBdN numeric(11,6),
AANUSEqN numeric(10,6),
AAOthrN numeric(10,6),
AAUSBdN numeric(11,6),
AAUSEqN numeric(11,6),
AAABN numeric(8,6),
AABondL numeric(15,6),
AACashL numeric(16,6),
AAEqL numeric(15,6),
AANUSBdL numeric(10,6),
AANUSEqL numeric(10,6),
AAOthrL numeric(15,6),
AAUSBdL numeric(10,6),
AAUSEqL numeric(10,6),
FoFIH varchar(3),
Leveragd varchar(3),
FeederFd varchar(3),
MasterFd varchar(3),
MasterN varchar(50),
MSTRFundID varchar(10),
Sharia varchar(3),
Ethical varchar(19),
ModelFd varchar(2),
Avail529 varchar(3),
AvailRet varchar(3),
AvailIns varchar(3),
TaxMgd varchar(3),
Contrarn varchar(3),
BrkAvail varchar(4000),
EnhIndex varchar(3),
Indexed varchar(3),
FoF varchar(3),
SocCons varchar(3),
NonDiv varchar(3),
ClsdAll varchar(3),
ClsdALLD Date,
ClsdNew varchar(3),
ClsdNewD Date,
FeeAccnt numeric(13,6),
FeeAdmin numeric(9,6),
FeeAdv numeric(9,6),
FeeAudit numeric(9,6),
FeeCust numeric(13,6),
FeeDistr numeric(13,6),
FeeIns numeric(9,6),
FeeLegal numeric(9,6),
FeeOrg numeric(9,6),
FeeOthr numeric(9,6),
FeePerf numeric(9,6),
FeeProf numeric(12,6),
FeeReg numeric(11,6),
FeeShRpt numeric(9,6),
FeeTA numeric(11,6),
Domicile varchar(15),
BaseCurr varchar(20),
ObsoltD Date,
ObsoltTy varchar(30),
DiscCurr numeric(9,6),
ShrType varchar(15),
AABdLR varchar(20),
AABdL varchar(20),
AACshLR varchar(20),
AACBLR varchar(20),
AAEqLR varchar(20),
AAxUSBLR varchar(20),
AAxUSELR varchar(20),
AAOtLR varchar(20),
AAPSLR varchar(20),
AAUSBLR varchar(20),
AAUSELR varchar(20)
)"""
mycursor.execute(sql)

# sqlFormula = "INSERT INTO people (name, age) VALUES (%s, %s)"
# manyPeople=[
# 	("name01", 15),
# ]

# mycursor.execute(sqlFormula, p1)

mydb.commit()
mydb.close()